development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: botofabulafia@gmail.com
  :password: abulafia76
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: botofabulafia@gmail.com
  :password: abulafia76
  :enable_starttls_auto: true